name: Lint

on:
  push:
    tags-ignore:
      - "**" # non eseguire il lint sui tag
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run ESLint
        run: npx --yes eslint@8.57.1 src/
