name: Lint

on:
  push:
    # branches: ['**'] per mantenere tutti i branch, escludendo solo i tag.
    # tags-ignore: ['**'] ignora le push sui tag, ma è necessario dichiarare tutti i branch
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Run ESLint
        run: npx --yes eslint@8.57.1 src/
