name: Release

on:
  workflow_dispatch: # Aggiunge la possibilità di avviare il workflow manualmente
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      ARTIFACT_NAME: "timbrapp-extension"
      CHROME_EXTENSION_ID: "dhpcliknphfdbocmcgfgepbkjmdklbgg"
      DEBUG_MODE: ${{ github.ref_type == 'tag' && 'false' || 'true' }}

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Package
        id: package
        run: |
          mv src $ARTIFACT_NAME
          sed -i "s/const DEBUG_MODE = .*/const DEBUG_MODE = $DEBUG_MODE;/g" $ARTIFACT_NAME/background.js
          cp LICENSE $ARTIFACT_NAME
          if [ "$DEBUG_MODE" = "false" ]; then
            echo "Minifying files..."
            curl -sLO https://github.com/tdewolff/minify/releases/download/v2.21.3/minify_linux_amd64.tar.gz
            tar -xzf minify_linux_amd64.tar.gz
            chmod +x ./minify
            ./minify -r -o $ARTIFACT_NAME/ $ARTIFACT_NAME/
            # NOTE skip json # find $ARTIFACT_NAME/ -type f \( -name "*.js" -o -name "*.css" -o -name "*.html" \) -exec ./minify -o {} {} \;
          else
            echo "Skipping minification..."
          fi
          zip -r $ARTIFACT_NAME.zip $ARTIFACT_NAME

      - name: Release
        id: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/v') # Esegui solo se è un tag
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          name: TimbrApp Extension ${{ github.ref_name }}
          body_path: changelog.md
          draft: false
          prerelease: false
          files: |
            ./${{ env.ARTIFACT_NAME }}.zip

      - name: Upload on Chrome Web Store
        uses: mnao305/chrome-extension-upload@v5.0.0
        # if: startsWith(github.ref, 'refs/tags/v') # Esegui solo se è un tag
        with:
          file-path: ./${{ env.ARTIFACT_NAME }}.zip
          extension-id: ${{ env.CHROME_EXTENSION_ID }}
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
          publish: false
